apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-proxy
spec:
  template:
    metadata:
      labels:
        app: postgres-proxy
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=blinky-196302:us-east1:blinky-c2=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: c2-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: c2
    spec:
      containers:
      - name: c2-server
        image: cr.io/blinky-196302/c2-image
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
          - name: DJANGO_SETTINGS_MODULE
            value: c2.settings.prod
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: c2-server
  labels:
    app: c2
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: c2
