# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('finished', 'finished')], default='pending', max_length=10)),
                ('run_start', models.DateTimeField(null=True)),
                ('result_time', models.DurationField(null=True)),
                ('result_status_code', models.IntegerField(null=True)),
                ('POP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.POP')),
                ('runner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pops.Process')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestRun')),
            ],
        ),
    ]
